// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IRegularBars: typeof import('~icons/regular/bars')['default']
    IRegularCalendarLines: typeof import('~icons/regular/calendar-lines')['default']
    IRegularCalendarLinesPen: typeof import('~icons/regular/calendar-lines-pen')['default']
    IRegularChevronLeft: typeof import('~icons/regular/chevron-left')['default']
    IRegularChevronRight: typeof import('~icons/regular/chevron-right')['default']
    IRegularChevronsLeft: typeof import('~icons/regular/chevrons-left')['default']
    IRegularChevronsRight: typeof import('~icons/regular/chevrons-right')['default']
    IRegularEye: typeof import('~icons/regular/eye')['default']
    IRegularFolder: typeof import('~icons/regular/folder')['default']
    IRegularImage: typeof import('~icons/regular/image')['default']
    IRegularPlus: typeof import('~icons/regular/plus')['default']
    IRegularShieldCheck: typeof import('~icons/regular/shield-check')['default']
    IRegularTag: typeof import('~icons/regular/tag')['default']
    ISolidAlien: typeof import('~icons/solid/alien')['default']
    ISolidBars: typeof import('~icons/solid/bars')['default']
    ISolidXmark: typeof import('~icons/solid/xmark')['default']
  }
}

export { }
