// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IBrandsBili: typeof import('~icons/brands/bili')['default']
    IBrandsBilibili: typeof import('~icons/brands/bilibili')['default']
    IBrandsGithub: typeof import('~icons/brands/github')['default']
    IBrandsGithubAlt: typeof import('~icons/brands/github-alt')['default']
    IBrandsSteam: typeof import('~icons/brands/steam')['default']
    IBrandsSteamSymbol: typeof import('~icons/brands/steam-symbol')['default']
    IRegularBars: typeof import('~icons/regular/bars')['default']
    IRegularBoxArchive: typeof import('~icons/regular/box-archive')['default']
    IRegularCalendarLines: typeof import('~icons/regular/calendar-lines')['default']
    IRegularCalendarLinesPen: typeof import('~icons/regular/calendar-lines-pen')['default']
    IRegularChevronLeft: typeof import('~icons/regular/chevron-left')['default']
    IRegularChevronRight: typeof import('~icons/regular/chevron-right')['default']
    IRegularChevronsLeft: typeof import('~icons/regular/chevrons-left')['default']
    IRegularChevronsRight: typeof import('~icons/regular/chevrons-right')['default']
    IRegularCircleCheck: typeof import('~icons/regular/circle-check')['default']
    IRegularEnvelope: typeof import('~icons/regular/envelope')['default']
    IRegularEye: typeof import('~icons/regular/eye')['default']
    IRegularFolder: typeof import('~icons/regular/folder')['default']
    IRegularFolders: typeof import('~icons/regular/folders')['default']
    IRegularGear: typeof import('~icons/regular/gear')['default']
    IRegularHome: typeof import('~icons/regular/home')['default']
    IRegularHouse: typeof import('~icons/regular/house')['default']
    IRegularImage: typeof import('~icons/regular/image')['default']
    IRegularLink: typeof import('~icons/regular/link')['default']
    IRegularLock: typeof import('~icons/regular/lock')['default']
    IRegularPlus: typeof import('~icons/regular/plus')['default']
    IRegularRightToBracket: typeof import('~icons/regular/right-to-bracket')['default']
    IRegularSpinnerThird: typeof import('~icons/regular/spinner-third')['default']
    IRegularTag: typeof import('~icons/regular/tag')['default']
    IRegularTags: typeof import('~icons/regular/tags')['default']
    IRegularUser: typeof import('~icons/regular/user')['default']
    IRegularXMark: typeof import('~icons/regular/x-mark')['default']
    ISolidAlien: typeof import('~icons/solid/alien')['default']
    ISolidBars: typeof import('~icons/solid/bars')['default']
    ISolidCircleSmall: typeof import('~icons/solid/circle-small')['default']
    ISolidCircleXmark: typeof import('~icons/solid/circle-xmark')['default']
    ISolidCircleXMark: typeof import('~icons/solid/circle-x-mark')['default']
    ISolidEnvelope: typeof import('~icons/solid/envelope')['default']
    ISolidFolderBlank: typeof import('~icons/solid/folder-blank')['default']
    ISolidXmark: typeof import('~icons/solid/xmark')['default']
  }
}

export { }
