// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IBrandsAlgolia: typeof import('~icons/brands/algolia')['default']
    IRegularHashTag: typeof import('~icons/regular/hash-tag')['default']
  }
}

export { }
